name: top_snackbar_flutter
description: Top snack bar package was created for nice and convenient way to inform users about what happened.
version: 3.3.0
homepage: https://github.com/LanarsInc/top-snackbar-flutter

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: